name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  test:
    name: Testing with ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.x']
        experimental: [false]
        include:
        - os: windows-latest
          python-version: '3.x'
          experimental: true
        - os: ubuntu-latest
          python-version: 'pypy@3.10'
          experimental: true

    steps:
    - uses: actions/checkout@v4
    - name: Install rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
    - name: Pin current Python version
      run: rye pin ${{ matrix.python-version }} && rye run python --version
    - name: Install dependencies
      run: rye sync
    - name: Run tests
      run: rye run pytest
